apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "c-nginx-helm.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "c-nginx-helm.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "c-nginx-helm.selectorLabels" . | nindent 6 }}
      {{- with .Values.podLabels }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "c-nginx-helm.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - image: "{{.Values.image.repository}}:{{.Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Values.containerName }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
