apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: c-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: c-nginx-c-nginx-helm
            port:
              number: 80